/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author alejandro
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPpal = new javax.swing.JPanel();
        EtiquetaA = new javax.swing.JLabel();
        InA = new javax.swing.JTextField();
        EtiquetaB = new javax.swing.JLabel();
        InB = new javax.swing.JTextField();
        EtiquetaC = new javax.swing.JLabel();
        InC = new javax.swing.JTextField();
        BotClear = new javax.swing.JButton();
        BotMas = new javax.swing.JButton();
        BotMenos = new javax.swing.JButton();
        BotMul = new javax.swing.JButton();
        BotDiv = new javax.swing.JButton();
        BotV = new javax.swing.JButton();
        BotR = new javax.swing.JButton();
        BotI = new javax.swing.JButton();
        BotA = new javax.swing.JButton();
        BotB = new javax.swing.JButton();
        BotC = new javax.swing.JButton();
        BotConcat = new javax.swing.JButton();
        UnidadA = new javax.swing.JLabel();
        UnidadB = new javax.swing.JLabel();
        UnidadC = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP Calculadora");
        setResizable(false);

        java.awt.GridBagLayout panelPpalLayout = new java.awt.GridBagLayout();
        panelPpalLayout.columnWidths = new int[] {64, 64, 64, 64, 16, 64, 64};
        panelPpal.setLayout(panelPpalLayout);

        EtiquetaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaA.setText("A =");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(EtiquetaA, gridBagConstraints);

        InA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InA.setToolTipText("");
        InA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(InA, gridBagConstraints);

        EtiquetaB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaB.setText("B =");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(EtiquetaB, gridBagConstraints);

        InB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(InB, gridBagConstraints);

        EtiquetaC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaC.setText("C =");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(EtiquetaC, gridBagConstraints);

        InC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(InC, gridBagConstraints);

        BotClear.setText("Limpiar");
        BotClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotClear, gridBagConstraints);

        BotMas.setText("+");
        BotMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotMasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotMas, gridBagConstraints);

        BotMenos.setText("-");
        BotMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotMenosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotMenos, gridBagConstraints);

        BotMul.setText("*");
        BotMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotMulActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotMul, gridBagConstraints);

        BotDiv.setText("/");
        BotDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotDivActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotDiv, gridBagConstraints);

        BotV.setText("V");
        BotV.setToolTipText("<html>\n<b>Calcular Voltaje</b>\n<ul>\n<li>A = Voltaje (voltios)</li>\n<li>B = Resistencia (ohmios)</li>\n<li>C = Corriente (amperios)</li>\n</ul>\n</html>");
        BotV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotV, gridBagConstraints);

        BotR.setText("R");
        BotR.setToolTipText("<html>\n<b>Calcular Resistencia</b>\n<ul>\n<li>A = Voltaje (voltios)</li>\n<li>B = Resistencia (ohmios)</li>\n<li>C = Corriente (amperios)</li>\n</ul>\n</html>");
        BotR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotR, gridBagConstraints);

        BotI.setText("I");
        BotI.setToolTipText("<html>\n<b>Calcular Corriente</b>\n<ul>\n<li>A = Voltaje (voltios)</li>\n<li>B = Resistencia (ohmios)</li>\n<li>C = Corriente (amperios)</li>\n</ul>\n</html>");
        BotI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotIActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotI, gridBagConstraints);

        BotA.setText("A");
        BotA.setToolTipText("<html>\n<b>Calcular Cateto</b>\n<ul>\n<li>A = Cateto A</li>\n<li>B = Cateto B</li>\n<li>C = Hipotenusa</li>\n</ul>\n</html>");
        BotA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotA, gridBagConstraints);

        BotB.setText("B");
        BotB.setToolTipText("<html>\n<b>Calcular Cateto</b>\n<ul>\n<li>A = Cateto A</li>\n<li>B = Cateto B</li>\n<li>C = Hipotenusa</li>\n</ul>\n</html>");
        BotB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotB, gridBagConstraints);

        BotC.setText("H");
        BotC.setToolTipText("<html>\n<b>Calcular Hipotenusa</b>\n<ul>\n<li>A = Cateto A</li>\n<li>B = Cateto B</li>\n<li>C = Hipotenusa</li>\n</ul>\n</html>");
        BotC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotC, gridBagConstraints);

        BotConcat.setText("Concatenar");
        BotConcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotConcatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(BotConcat, gridBagConstraints);

        UnidadA.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        UnidadA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UnidadA.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(UnidadA, gridBagConstraints);

        UnidadB.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        UnidadB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UnidadB.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(UnidadB, gridBagConstraints);

        UnidadC.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        UnidadC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UnidadC.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPpal.add(UnidadC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 2, 8, 2);
        panelPpal.add(jSeparator1, gridBagConstraints);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        panelPpal.add(jSeparator2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Liberation Mono", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAS - Programacion III - Ismael Tolaba");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 2, 0, 2);
        panelPpal.add(jLabel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InAActionPerformed

    private void BotClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotClearActionPerformed
        // Limpiar campos
        String valA = InA.getText(), valB = InB.getText();
        InA.setText("");
        InB.setText("");
        InC.setText("");
        
        indicarUnidades("...","...","...");
        
        if("o".equals(valA) && "o".equals(valB)){
            InC.setText("o-limpiadas");
        }
    }//GEN-LAST:event_BotClearActionPerformed

    private void BotMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotMasActionPerformed
      // Sumar valores de campo A y B y mostrar el resultado en C
      String StrA, StrB;
      double ValA, ValB, ValC;

      StrA = InA.getText();
      StrB = InB.getText();

      // Verificar si A y B son Numéricos
      if(isNumeric(StrA) && isNumeric(StrB)){
        ValA = Double.parseDouble(StrA);
        ValB = Double.parseDouble(StrB);
        ValC = ValA + ValB;
        InC.setText(String.valueOf(ValC));
      } else {
        InC.setText("Error");
      }
      
      indicarUnidades("...", "...", "...");
      
      if("mago".equals(InA.getText()) && "comer".equals(InB.getText())) {
          InC.setText("magordito");
      }
    }//GEN-LAST:event_BotMasActionPerformed

  private void BotMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotMenosActionPerformed
    /* Restar valores de campo A y B y mostrar el resultado en C */
    String StrA, StrB;
    double ValA, ValB, ValC;

    StrA = InA.getText();
    StrB = InB.getText();

    // Verificar si A y B son Numéricos
    if(isNumeric(StrA) && isNumeric(StrB)){
      ValA = Double.parseDouble(StrA);
      ValB = Double.parseDouble(StrB);
      ValC = ValA - ValB;
      InC.setText(String.valueOf(ValC));
    } else {
      InC.setText("Error");
    }
    
    indicarUnidades("...", "...", "...");
    
    if("septiembre".equals(InA.getText()) && "tu".equals(InB.getText())) {
        InC.setText("sepembre");
    }
  }//GEN-LAST:event_BotMenosActionPerformed

  private void BotMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotMulActionPerformed
    /* Multiplicar valores de campo A y B y mostrar el resultado en C */
    String StrA, StrB;
    double ValA, ValB, ValC;

    StrA = InA.getText();
    StrB = InB.getText();

    // Verificar si A y B son Numéricos
    if(isNumeric(StrA) && isNumeric(StrB)){
      ValA = Double.parseDouble(StrA);
      ValB = Double.parseDouble(StrB);
      ValC = ValA * ValB;
      InC.setText(String.valueOf(ValC));
    } else {
      InC.setText("Error");
    }
    
    indicarUnidades("...", "...", "...");
  }//GEN-LAST:event_BotMulActionPerformed

  private void BotDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotDivActionPerformed
    /* Dividir valores de campo A y B y mostrar el resultado en C */
    String StrA, StrB;
    double ValA, ValB, ValC;

    StrA = InA.getText();
    StrB = InB.getText();

    // Verificar si A y B son Numéricos
    if(isNumeric(StrA) && isNumeric(StrB)){
      ValA = Double.parseDouble(StrA);
      ValB = Double.parseDouble(StrB);
      if(ValB > 0){
        ValC = ValA / ValB;
        InC.setText(String.valueOf(ValC));          
      } else {
        InC.setText("E: Division entre 0");
      }
    } else {
      InC.setText("Error");
    }
    
    indicarUnidades("...", "...", "...");
    
    if("Metallica".equals(InA.getText())) {
        InB.setText("Metallica");
        InC.setText("Megadeath");
    }
  }//GEN-LAST:event_BotDivActionPerformed

  private void BotConcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotConcatActionPerformed
    /* Concatenar A y B en C */
    InC.setText(InA.getText() + InB.getText());
    indicarUnidades("...", "...", "...");
    
    if("Ismael".equals(InA.getText()) && "Tolaba".equals(InB.getText())) {
        InC.setText("El programador");
    }
    if("Emanuel".equals(InA.getText()) && "Rodríguez".equals(InB.getText())) {
        InC.setText("El profesor");
    }
  }//GEN-LAST:event_BotConcatActionPerformed

  private void BotVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotVActionPerformed
    /*
     *  Calcular el valor de A (Voltaje) a partir de los valores de B (resistencia)
     *  y C (Corriente)
     */
    String StrB, StrC;
    double ValA, ValB, ValC;

    StrB = InB.getText();
    StrC = InC.getText();

    // Verificar si B y C son Numéricos
    if(isNumeric(StrB) && isNumeric(StrC)){
      ValB = Double.parseDouble(StrB);
      ValC = Double.parseDouble(StrC);
      ValA = ValB * ValC;
      InA.setText(String.valueOf(ValA));
    } else {
      InA.setText("Error");
    }
    
    indicarUnidades("V", "Ω", "A");
  }//GEN-LAST:event_BotVActionPerformed

  private void BotRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRActionPerformed
    /*
     *  Calcular el valor de B (Resistencia) a partir de los valores de A (Voltaje)
     *  y C (Corriente)
     */
    String StrA, StrC;
    double ValA, ValB, ValC;

    StrA = InA.getText();
    StrC = InC.getText();

    // Verificar si A y C son Numéricos
    if(isNumeric(StrA) && isNumeric(StrC)){
      ValA = Double.parseDouble(StrA);
      ValC = Double.parseDouble(StrC);
      if(ValC>0){
        ValB = ValA / ValC;
        InB.setText(String.valueOf(ValB));
      } else {
        InB.setText("E: Division por 0");
      }
    } else {
      InB.setText("Error");
    }
    
    indicarUnidades("V", "Ω", "A");
  }//GEN-LAST:event_BotRActionPerformed

    private void BotIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotIActionPerformed
        /*
         *  Calcular el valor de C (Corriente) a partir de los valores de A (Voltaje)
         *  y B (Resistencia)
         */
        String StrA, StrB;
        double ValA, ValB, ValC;

        StrA = InA.getText();
        StrB = InB.getText();

        // Verificar si A y B son Numéricos
        if(isNumeric(StrA) && isNumeric(StrB)){
          ValA = Double.parseDouble(StrA);
          ValB = Double.parseDouble(StrB);
          if(ValB>0){
            ValC = ValA / ValB;
            InC.setText(String.valueOf(ValC));
          } else {
            InB.setText("E: Division por 0");
          }
        } else {
          InB.setText("Error");
        }

        indicarUnidades("V", "Ω", "A");
    }//GEN-LAST:event_BotIActionPerformed

    private void BotAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAActionPerformed
        /* Calcular lado A de un Triangulo rectangulo */
        String StrB, StrC;
        double ValA, ValB, ValC;
        
        StrB = InB.getText();
        StrC = InC.getText();
        
        // verificar si B y C son numéricos
        if(isNumeric(StrB) && isNumeric(StrC)){
            ValB = Double.parseDouble(StrB);
            ValC = Double.parseDouble(StrC);
            ValA = Math.sqrt(-(ValB * ValB) + (ValC * ValC));
            
            InA.setText(String.valueOf(ValA));
        }
        
        indicarUnidades("...", "...", "...");
    }//GEN-LAST:event_BotAActionPerformed

    private void BotBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBActionPerformed
        /* Calcular lado B de un Triangulo rectangulo */
        String StrA, StrC;
        double ValA, ValB, ValC;
        
        StrA = InA.getText();
        StrC = InC.getText();
        
        // verificar si A y C son numéricos
        if(isNumeric(StrA) && isNumeric(StrC)){
            ValA = Double.parseDouble(StrA);
            ValC = Double.parseDouble(StrC);
            ValB = Math.sqrt(-(ValA * ValA) + (ValC * ValC));
            
            InB.setText(String.valueOf(ValB));
        }
        
        indicarUnidades("...", "...", "...");
    }//GEN-LAST:event_BotBActionPerformed

    private void BotCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCActionPerformed
        /* Calcular ipotenusa de un triangulo rectangulo */
        String StrA, StrB;
        double ValA, ValB, ValC;
        
        StrA = InA.getText();
        StrB = InB.getText();
        
        // verificar si A y B son numéricos
        if(isNumeric(StrA) && isNumeric(StrB)){
            ValA = Double.parseDouble(StrA);
            ValB = Double.parseDouble(StrB);
            ValC = Math.sqrt((ValA * ValA) + (ValB * ValB));
            
            InC.setText(String.valueOf(ValC));
        }
        
        indicarUnidades("...", "...", "...");
    }//GEN-LAST:event_BotCActionPerformed
    
  public static boolean isNumeric(String strNum) {
    if (strNum == null) {
      return false;
    }
    try {
      double d = Double.parseDouble(strNum);
    } catch (NumberFormatException nfe) {
      return false;
    }
    return true;
  }
  
  private void indicarUnidades(String UA, String UB, String UC){
    UnidadA.setText(UA);
    UnidadB.setText(UB);
    UnidadC.setText(UC);
  }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotA;
    private javax.swing.JButton BotB;
    private javax.swing.JButton BotC;
    private javax.swing.JButton BotClear;
    private javax.swing.JButton BotConcat;
    private javax.swing.JButton BotDiv;
    private javax.swing.JButton BotI;
    private javax.swing.JButton BotMas;
    private javax.swing.JButton BotMenos;
    private javax.swing.JButton BotMul;
    private javax.swing.JButton BotR;
    private javax.swing.JButton BotV;
    private javax.swing.JLabel EtiquetaA;
    private javax.swing.JLabel EtiquetaB;
    private javax.swing.JLabel EtiquetaC;
    private javax.swing.JTextField InA;
    private javax.swing.JTextField InB;
    private javax.swing.JTextField InC;
    private javax.swing.JLabel UnidadA;
    private javax.swing.JLabel UnidadB;
    private javax.swing.JLabel UnidadC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelPpal;
    // End of variables declaration//GEN-END:variables
}
